### ISSUE TITLE
Can purchase items when there is no inventory space.

### ISSUE THREAD

**Issue by Tevish** [ZaneDubya/CommunityKitPublic#273]
Items purchased do not appear and there's no stop to purchasing when inventory is full.

**Comment by ZaneDubya** [comment]
Who knows where those items are going! Bag of holding, perhaps? The Upside Down?

I can fix that easily! Thank you!

**Comment by Tevish** [comment]
Glad to help! :-)

**Comment by ZaneDubya** [comment]
The items are going into your loot sheet 😆

**Comment by Tevish** [comment]
Interesting! My background is in chemistry and IT. I only enough coding to make myself look silly trying to pretend I understand more than the concepts. ;-) I can't imagine how you reworked this project! Impressive!

**Comment by ZaneDubya** [comment]
It's been a huge learning experience for me and I'm so excited to be back in the Cano with people! This is the first project I've released since FauxINN in 2003. That only ran for a few months; I'm hoping to keep this up for as long as people are interested in playing. :)

I fixed the bug you found locally - now, you'll get an error message if you attempt to buy an item that you cannot afford, or when you don't have enough space in your inventory. I'll push it out later tonight. Thank you!
