### ISSUE TITLE
False positive: Virus Total flags exe as CIL.StupidCryptor.Heur

### ISSUE THREAD

**Issue by AthasOrBust** [ZaneDubya/CommunityKitPublic#408]
Hello,

I uploaded the CommunityClient.exe to Virus Total (www.virustotal.com) and one of the detection engines (VBA32) is reporting a virus of the type CIL.StupidCryptor.Heur. I'm aware that this is likely a false positive but I thought I'd report it here for consideration.

Direct link to the details of the scan can be found here: https://www.virustotal.com/#/file/770e70c8e08331489a708cbd5367eb5b120c43744d9bfe56c7b05519b4215b67/details

**Comment by ZaneDubya** [comment]
Thank you for submitting this! This happens because VBA32 thinks that anybody who obfuscates their source code is up to no good. I've played with the obfuscation settings and there's no way to get under the threshold for this alert without - well - not doing it at all. I wonder if there's some white list I could get on...

**Comment by ZaneDubya** [comment]
I'm changing the title so people aren't misled about the false positive.

**Comment by AthasOrBust** [comment]
I have no experience with this but given other threads I've read about false positives for games you're going to have to contact the anti-virus vendor directly and get them to vet it. That can be a long and time-consuming process but possibly worth it? Unfortunately there's no industry-wide whitelist I'm aware of so it normally has to be done per vendor.

Can't really comment on what VBA32 focus on, have little knowledge of them beyond Virus Total.

**Comment by ZaneDubya** [comment]
Fixed in 192:

https://virusscan.jotti.org/en-US/filescanjob/2wwyp27tbe:
![Screen Shot 2019-05-24 at 12 06 19 PM](https://user-images.githubusercontent.com/7041719/58344838-629ab180-7e1c-11e9-80df-42a8a18ecb07.png)

https://www.virustotal.com/#/file/65af3f4d2d4248968fced2fe8f00678150221459731f14f56594e93f71469aa4/detection:
![Screen Shot 2019-05-24 at 12 06 10 PM](https://user-images.githubusercontent.com/7041719/58344846-6cbcb000-7e1c-11e9-809e-dc9fc8c80dee.png)

http://r.virscan.org/language/en/report/10d6431381bce6afeda777e53caefe07:
![Screen Shot 2019-05-24 at 12 07 33 PM](https://user-images.githubusercontent.com/7041719/58344892-8fe75f80-7e1c-11e9-9c7c-31215304cb5c.png)
